# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  typescript:
    image: node:16
    # restart: always
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    command: bash -c "npm install && npx tsc --watch"

  node:
    image: node:16
    # restart: always
    working_dir: /home/node/app
    ports:
      - 4000:4000
    volumes:
      - ./backend:/home/node/app
    command: bash -c "npm install && npx tsc && npx nodemon"

  frontend:
    image: node:16
    working_dir: /home/node/app
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/app
    command: bash -c "npm install && npm start"

  nginx:
    image: nginx
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/html:/html
    ports:
    - "8080:8080"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=8080
